---
# tasks file for roles/general
- name: Generate nomad general config.
  ansible.builtin.template:
    src: "{{ role.path }}/templates/nomad.hcl.j2"
    dest: "/etc/nomad.d/nomad.hcl"
    owner: ubuntu
    group: root
    mode: '0600'