---
# tasks file for roles/server
- name: Generate nomad server config.
  ansible.builtin.template:
    src: "{{ role.path }}/templates/server.hcl.j2"
    dest: "/etc/nomad.d/server.hcl"
    owner: ubuntu
    group: root
    mode: '0600'